# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy-github:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Prepare and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PAGES_TOKEN }}
        run: |
          npm install
          npm run ng -- deploy --repo=https://github.com/yanghu/flight-pages.git --base-href=/flight-pages/ --name="Yang Hu" --email="hueyhy@gmail.com" --no-silent
          
  # build job
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '10.x'
      # Install the dependencies need to build the app
      - name: Install Dependencies
        run: npm install
      # Runs a set of commands to build
      - name: Build
        run: npm run build --prod
      # sotre the artifact
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy-firebae:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download a single artifact
        uses: actions/download-artifact@v2
#       - name: Setup tmate session
#         uses: mxschmitt/action-tmate@v3
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID : fsimdash   

